spring:
  application:
    name: greeting-service
  profiles:
    active: dev
boot:
  logstash:
    destination: localhost:5044
    custom-fields: |-
      {"appname":"${spring.application.name}", "env": "${spring.profiles.active}"}
    queue-size: 512
